import type { ContentLocale } from "@/lib/site";

type InsightsCopy = {
  eyebrow: string;
  title: string;
  description: string;
  latest: string;
  readArticle: string;
  minutes: string;
  emptyTitle: string;
  emptyBody: string;
  back: string;
  fallbackNotice: string;
  published: string;
  updated: string;
  kinds: Record<"NEWS" | "GUIDE" | "CASE_STUDY", string>;
  seoTitle: string;
  seoDescription: string;
};

export const insightsCopy: Record<ContentLocale, InsightsCopy> = {
  en: { eyebrow: "Insights & resources", title: "Flooring knowledge for better sourcing decisions", description: "Practical guides, material insights and project lessons for distributors, importers, architects and private-label flooring teams.", latest: "Latest insights", readArticle: "Read article", minutes: "min read", emptyTitle: "Insights are being prepared", emptyBody: "Published articles will appear here automatically.", back: "Back to insights", fallbackNotice: "This article is not yet available in your selected language. The English source is shown.", published: "Published", updated: "Updated", kinds: { NEWS: "Company news", GUIDE: "Buying guide", CASE_STUDY: "Case study" }, seoTitle: "Flooring Insights, Buying Guides & Project Knowledge", seoDescription: "Explore TOOYEI flooring guides, material knowledge, sourcing advice and project insights for global B2B buyers." },
  de: { eyebrow: "Wissen & Ressourcen", title: "Bodenwissen für bessere Beschaffungsentscheidungen", description: "Praxisnahe Leitfäden, Materialwissen und Projekterfahrungen für Händler, Importeure, Architekten und Eigenmarken.", latest: "Neueste Beiträge", readArticle: "Artikel lesen", minutes: "Min. Lesezeit", emptyTitle: "Beiträge werden vorbereitet", emptyBody: "Veröffentlichte Beiträge erscheinen hier automatisch.", back: "Zurück zu den Beiträgen", fallbackNotice: "Dieser Artikel ist noch nicht auf Deutsch verfügbar. Die englische Quelle wird angezeigt.", published: "Veröffentlicht", updated: "Aktualisiert", kinds: { NEWS: "Unternehmensnews", GUIDE: "Einkaufsleitfaden", CASE_STUDY: "Fallstudie" }, seoTitle: "Bodenwissen, Einkaufsleitfäden und Projektpraxis", seoDescription: "Leitfäden, Materialwissen und Beschaffungstipps von TOOYEI für internationale B2B-Einkäufer." },
  fr: { eyebrow: "Analyses et ressources", title: "Des connaissances pour mieux acheter vos revêtements de sol", description: "Guides pratiques, analyses matériaux et retours de projet pour distributeurs, importateurs, architectes et marques privées.", latest: "Derniers articles", readArticle: "Lire l’article", minutes: "min de lecture", emptyTitle: "Les articles sont en préparation", emptyBody: "Les articles publiés apparaîtront automatiquement ici.", back: "Retour aux articles", fallbackNotice: "Cet article n’est pas encore disponible en français. La version anglaise est affichée.", published: "Publié", updated: "Mis à jour", kinds: { NEWS: "Actualités", GUIDE: "Guide d’achat", CASE_STUDY: "Étude de cas" }, seoTitle: "Guides et connaissances sur les revêtements de sol", seoDescription: "Découvrez les guides, conseils d’approvisionnement et analyses matériaux TOOYEI pour les acheteurs B2B." },
  es: { eyebrow: "Ideas y recursos", title: "Conocimiento para tomar mejores decisiones de compra", description: "Guías prácticas, conocimiento de materiales y aprendizajes de proyectos para distribuidores, importadores, arquitectos y marcas privadas.", latest: "Últimos artículos", readArticle: "Leer artículo", minutes: "min de lectura", emptyTitle: "Estamos preparando los artículos", emptyBody: "Los artículos publicados aparecerán aquí automáticamente.", back: "Volver a artículos", fallbackNotice: "Este artículo aún no está disponible en español. Se muestra la fuente en inglés.", published: "Publicado", updated: "Actualizado", kinds: { NEWS: "Noticias", GUIDE: "Guía de compra", CASE_STUDY: "Caso de estudio" }, seoTitle: "Guías y conocimiento sobre suelos", seoDescription: "Guías de suelos, conocimiento de materiales y consejos de compra TOOYEI para compradores B2B internacionales." },
  ru: { eyebrow: "Экспертиза и материалы", title: "Знания о напольных покрытиях для уверенных закупок", description: "Практические руководства, материалы и опыт проектов для дистрибьюторов, импортёров, архитекторов и собственных брендов.", latest: "Новые материалы", readArticle: "Читать", minutes: "мин чтения", emptyTitle: "Материалы готовятся", emptyBody: "Опубликованные статьи появятся здесь автоматически.", back: "К списку материалов", fallbackNotice: "Статья пока недоступна на русском языке. Показана английская версия.", published: "Опубликовано", updated: "Обновлено", kinds: { NEWS: "Новости компании", GUIDE: "Руководство", CASE_STUDY: "Кейс" }, seoTitle: "Материалы, руководства и знания о напольных покрытиях", seoDescription: "Руководства TOOYEI по материалам, закупкам и проектам для международных B2B-покупателей." },
  ja: { eyebrow: "インサイト・資料", title: "より良い床材調達判断のための専門知識", description: "販売店、輸入業者、設計者、プライベートブランド向けの実践ガイド、素材知識、プロジェクト事例です。", latest: "最新記事", readArticle: "記事を読む", minutes: "分で読めます", emptyTitle: "記事を準備中です", emptyBody: "公開された記事は自動的にここへ表示されます。", back: "記事一覧へ戻る", fallbackNotice: "この記事はまだ日本語化されていません。英語の原文を表示しています。", published: "公開日", updated: "更新日", kinds: { NEWS: "企業ニュース", GUIDE: "調達ガイド", CASE_STUDY: "事例" }, seoTitle: "床材インサイト・調達ガイド・プロジェクト知識", seoDescription: "グローバルB2Bバイヤー向けのTOOYEI床材ガイド、素材知識、調達アドバイスをご覧ください。" },
  it: { eyebrow: "Approfondimenti e risorse", title: "Conoscenze per migliori decisioni di approvvigionamento", description: "Guide pratiche, conoscenza dei materiali e lezioni di progetto per distributori, importatori, architetti e private label.", latest: "Ultimi articoli", readArticle: "Leggi l’articolo", minutes: "min di lettura", emptyTitle: "Gli articoli sono in preparazione", emptyBody: "Gli articoli pubblicati appariranno qui automaticamente.", back: "Torna agli articoli", fallbackNotice: "Questo articolo non è ancora disponibile in italiano. Viene mostrata la fonte inglese.", published: "Pubblicato", updated: "Aggiornato", kinds: { NEWS: "Notizie", GUIDE: "Guida all’acquisto", CASE_STUDY: "Caso studio" }, seoTitle: "Guide e conoscenze sui pavimenti", seoDescription: "Guide TOOYEI, conoscenza dei materiali e consigli di approvvigionamento per acquirenti B2B internazionali." },
  ar: { eyebrow: "معرفة وموارد", title: "معرفة تساعد على اتخاذ قرارات توريد أفضل", description: "أدلة عملية ومعرفة بالمواد ودروس مشاريع للموزعين والمستوردين والمهندسين والعلامات الخاصة.", latest: "أحدث المقالات", readArticle: "اقرأ المقال", minutes: "دقيقة قراءة", emptyTitle: "المقالات قيد الإعداد", emptyBody: "ستظهر المقالات المنشورة هنا تلقائياً.", back: "العودة إلى المقالات", fallbackNotice: "هذا المقال غير متاح بالعربية بعد. يتم عرض المصدر الإنجليزي.", published: "نُشر", updated: "حُدّث", kinds: { NEWS: "أخبار الشركة", GUIDE: "دليل شراء", CASE_STUDY: "دراسة حالة" }, seoTitle: "معرفة الأرضيات وأدلة الشراء والمشاريع", seoDescription: "استكشف أدلة TOOYEI ومعرفة المواد ونصائح التوريد للمشترين الدوليين بين الشركات." },
  zh: { eyebrow: "专业洞察与资源", title: "帮助全球买家做出更好地板采购决策", description: "为经销商、进口商、建筑师和自有品牌团队提供采购指南、材料知识与项目经验。", latest: "最新文章", readArticle: "阅读文章", minutes: "分钟阅读", emptyTitle: "文章正在准备中", emptyBody: "后台发布文章后将自动显示在这里。", back: "返回文章中心", fallbackNotice: "该文章暂未完成中文版本，当前显示英文源内容。", published: "发布于", updated: "更新于", kinds: { NEWS: "企业动态", GUIDE: "采购指南", CASE_STUDY: "案例研究" }, seoTitle: "地板知识、采购指南与项目洞察", seoDescription: "浏览 TOOYEI 面向国际 B2B 买家的地板采购指南、材料知识、选品建议与项目洞察。" },
};
