CREATE TABLE IF NOT EXISTS "SiteSetting" (
  "id" TEXT NOT NULL DEFAULT 'site',
  "siteName" TEXT NOT NULL,
  "legalName" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "siteUrl" TEXT NOT NULL,
  "defaultSeoTitle" TEXT NOT NULL,
  "defaultSeoDescription" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "whatsappDisplay" TEXT NOT NULL,
  "address" TEXT,
  "inquiryEmail" TEXT,
  "notificationEmail" TEXT,
  "timezone" TEXT NOT NULL DEFAULT 'Asia/Shanghai',
  "defaultLocale" TEXT NOT NULL DEFAULT 'zh',
  "allowIndexing" BOOLEAN NOT NULL DEFAULT true,
  "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SiteSetting_pkey" PRIMARY KEY ("id")
);

INSERT INTO "SiteSetting" (
  "id",
  "siteName",
  "legalName",
  "description",
  "siteUrl",
  "defaultSeoTitle",
  "defaultSeoDescription",
  "email",
  "phone",
  "whatsappDisplay",
  "address",
  "inquiryEmail",
  "notificationEmail",
  "timezone",
  "defaultLocale",
  "allowIndexing",
  "maintenanceMode"
) VALUES (
  'site',
  'TOOYEI',
  'Changzhou Tooyei New Material Co., Ltd.',
  'Factory-direct SPC, WPC, LVT and laminate flooring for wholesale, commercial and OEM projects.',
  COALESCE(NULLIF(current_setting('app.site_url', true), ''), 'https://www.tooyei.com'),
  'Tooyei 专业地板制造商',
  '工厂直供 SPC、WPC、LVT 与强化地板，为批发、商业和 OEM 项目提供稳定品质与出口服务。',
  'kitty@tooyei.com',
  '+86 180 1505 7611',
  '+86 180 1500 7771',
  'Changzhou, Jiangsu, China',
  'kitty@tooyei.com',
  'kitty@tooyei.com',
  'Asia/Shanghai',
  'zh',
  true,
  false
) ON CONFLICT ("id") DO NOTHING;
