import { siteConfig, type Locale } from "@/lib/site";

export type PolicyKind = "privacy" | "terms" | "cookies";

export type PolicyCopy = {
  eyebrow: string;
  title: string;
  intro: string;
  description: string;
  lastUpdatedLabel: string;
  lastUpdated: string;
  backHome: string;
  sections: Array<{ title: string; body: string }>;
};

const email = siteConfig.email;
const legalName = siteConfig.legalName;
const updated = "2026-07-18";

export const policies: Record<Locale, Record<PolicyKind, PolicyCopy>> = {
  zh: {
    privacy: {
      eyebrow: "法律 / 隐私",
      title: "隐私政策",
      intro: "本政策说明 TOOYEI 官网和后台相关业务流程如何处理您主动提交的业务信息。",
      description: "了解 TOOYEI 如何收集、使用、保护和处理客户咨询、项目沟通与网站访问相关信息。",
      lastUpdatedLabel: "最后更新",
      lastUpdated: updated,
      backHome: "返回首页",
      sections: [
        { title: "适用范围与负责人", body: `${legalName} 负责本网站相关信息处理。本政策适用于官网咨询、邮件沟通、样品、报价、项目协作及后台运营所需的必要业务信息。` },
        { title: "我们收集的信息", body: "当您提交表单或联系 TOOYEI 时，我们可能收集姓名、公司、职位、邮箱、电话、国家或地区、目标市场、产品需求、项目资料以及您主动提供的附件或留言。" },
        { title: "信息使用目的", body: "信息用于回复咨询、确认产品规格、准备样品或报价、安排出口协作、维护客户沟通记录、改进网站体验，以及履行法律、合规或安全要求。" },
        { title: "共享与跨境处理", body: "我们仅在业务必要范围内与内部团队、物流、检测、支付、IT 或合规服务方共享信息。由于 TOOYEI 服务全球客户，相关信息可能在不同国家或地区处理。" },
        { title: "保留、安全与您的权利", body: "我们会在业务合作、合规和审计所需期限内保留信息，并采取合理访问控制。您可请求查询、更正、删除或限制处理您的信息。" },
        { title: "未成年人、更新与联系", body: `本网站面向企业业务，不主动面向未成年人。政策更新会发布在本页面。如有隐私请求，请联系 ${email}。` },
      ],
    },
    terms: {
      eyebrow: "法律 / 条款",
      title: "使用条款",
      intro: "访问或使用本网站，即表示您同意遵守以下使用规则。",
      description: "TOOYEI 网站使用条款，说明网站内容、知识产权、使用限制、外部链接和责任边界。",
      lastUpdatedLabel: "最后更新",
      lastUpdated: updated,
      backHome: "返回首页",
      sections: [
        { title: "接受条款", body: `本网站由 ${legalName} 运营。访问网站、提交咨询或使用网站内容时，您应遵守本条款及适用法律。` },
        { title: "网站内容与业务确认", body: "网站中的产品图片、规格、认证、颜色、包装和应用说明用于一般介绍，不构成不可撤销报价。具体交易条件以双方最终书面确认文件为准。" },
        { title: "知识产权", body: "除另有说明外，网站中的品牌标识、文字、图片、页面设计和资料归 TOOYEI 或相关权利方所有。未经许可不得复制、误导性展示或用于竞争性商业宣传。" },
        { title: "可接受使用", body: "您不得利用网站上传恶意内容、干扰服务、抓取敏感数据、冒充 TOOYEI 或以违反法律、贸易合规和平台安全的方式使用网站。" },
        { title: "第三方链接", body: "网站可能包含社交媒体、地图、邮件、下载或第三方工具链接。第三方服务由其自身条款、隐私政策和可用性约束。" },
        { title: "免责声明、责任与更新", body: `我们努力保持信息准确，但不保证网站持续无误或完全不中断。条款可能随业务流程更新，如有问题请联系 ${email}。` },
      ],
    },
    cookies: {
      eyebrow: "法律 / COOKIES",
      title: "Cookies 说明",
      intro: "本页面说明 TOOYEI 网站可能使用的 Cookie 与类似本地存储技术。",
      description: "TOOYEI Cookies 说明，包含必要功能、偏好设置、分析工具、浏览器管理和联系方式。",
      lastUpdatedLabel: "最后更新",
      lastUpdated: updated,
      backHome: "返回首页",
      sections: [
        { title: "Cookie 是什么", body: "Cookie 和类似技术会在浏览器中保存少量信息，用于识别会话、记住语言偏好或支持基础网站功能。" },
        { title: "必要 Cookie", body: "必要 Cookie 用于安全、后台登录、表单提交、语言选择和基础交互。缺少这些信息，部分功能可能无法正常运行。" },
        { title: "偏好设置", body: "网站可能保存您选择的语言、地区或界面偏好，以减少重复选择并改善浏览体验。" },
        { title: "分析与营销", body: "如未来启用分析或营销工具，我们会根据适用要求更新说明，并在需要时提供同意或控制选项。" },
        { title: "如何管理", body: "您可以通过浏览器设置查看、阻止或删除 Cookie。禁用必要 Cookie 可能影响登录、表单或语言切换。" },
        { title: "更新与联系", body: `我们会随网站功能更新本说明。如对 Cookie 使用有疑问，请联系 ${email}。` },
      ],
    },
  },
  en: {
    privacy: {
      eyebrow: "Legal / Privacy",
      title: "Privacy Policy",
      intro: "This policy explains how TOOYEI handles business information you submit through our website and related workflows.",
      description: "How TOOYEI collects, uses, protects and handles enquiry, project and website information.",
      lastUpdatedLabel: "Last updated",
      lastUpdated: updated,
      backHome: "Back to home",
      sections: [
        { title: "Scope and controller", body: `${legalName} is responsible for information processed through this website, including enquiries, emails, samples, quotations, project coordination and necessary admin operations.` },
        { title: "Information we collect", body: "We may collect your name, company, role, email, phone, country or region, target market, product requirements, project files, attachments and messages you choose to provide." },
        { title: "How we use information", body: "We use information to reply to enquiries, confirm specifications, prepare samples or quotations, coordinate export work, keep communication records, improve the site and meet legal, compliance or security requirements." },
        { title: "Sharing and international processing", body: "We share information only where needed with internal teams and service providers such as logistics, testing, payment, IT and compliance partners. Because we serve global customers, information may be processed across countries or regions." },
        { title: "Retention, security and rights", body: "We keep information for business, compliance and audit needs and apply reasonable access controls. You may request access, correction, deletion or restriction of your information." },
        { title: "Minors, updates and contact", body: `This website is intended for business users and is not directed to minors. Updates will be posted here. Privacy requests can be sent to ${email}.` },
      ],
    },
    terms: {
      eyebrow: "Legal / Terms",
      title: "Terms of Use",
      intro: "By accessing or using this website, you agree to the following basic terms.",
      description: "TOOYEI website terms covering content, intellectual property, acceptable use, third-party links and liability limits.",
      lastUpdatedLabel: "Last updated",
      lastUpdated: updated,
      backHome: "Back to home",
      sections: [
        { title: "Acceptance", body: `This website is operated by ${legalName}. By visiting, submitting enquiries or using website content, you agree to follow these terms and applicable laws.` },
        { title: "Website content", body: "Product images, specifications, certifications, colors, packaging and application notes are general information and are not a binding offer. Final commercial terms are based on written confirmation between the parties." },
        { title: "Intellectual property", body: "Unless stated otherwise, trademarks, text, images, page layouts and materials belong to TOOYEI or the relevant rights holders and may not be copied or used in misleading commercial promotion without permission." },
        { title: "Acceptable use", body: "You must not upload malicious content, interfere with the service, scrape sensitive data, impersonate TOOYEI or use the site in a way that breaches law, trade compliance or platform security." },
        { title: "Third-party links", body: "The site may link to social media, maps, email, downloads or third-party tools. Those services are governed by their own terms, privacy policies and availability." },
        { title: "Disclaimer, liability and updates", body: `We work to keep information accurate, but do not guarantee the site will always be error-free or uninterrupted. These terms may be updated. Contact ${email} with questions.` },
      ],
    },
    cookies: {
      eyebrow: "Legal / Cookies",
      title: "Cookies Notice",
      intro: "This page explains cookies and similar local storage technologies that may be used on the TOOYEI website.",
      description: "TOOYEI cookies notice covering essential functions, preferences, analytics, browser controls and contact details.",
      lastUpdatedLabel: "Last updated",
      lastUpdated: updated,
      backHome: "Back to home",
      sections: [
        { title: "What cookies are", body: "Cookies and similar technologies store small amounts of information in your browser to recognize sessions, remember language preferences or support basic website features." },
        { title: "Essential cookies", body: "Essential cookies support security, admin login, form submission, language selection and core interactions. Some functions may not work without them." },
        { title: "Preferences", body: "The site may remember your language, region or interface preferences to reduce repeated selections and improve browsing." },
        { title: "Analytics and marketing", body: "If analytics or marketing tools are added in the future, this notice will be updated and consent or control options will be provided where required." },
        { title: "Managing cookies", body: "You can view, block or delete cookies in your browser settings. Disabling essential cookies may affect login, forms or language switching." },
        { title: "Updates and contact", body: `We update this notice as site features change. Questions about cookies can be sent to ${email}.` },
      ],
    },
  },
  de: {
    privacy: {
      eyebrow: "Rechtliches / Datenschutz",
      title: "Datenschutzerklärung",
      intro: "Diese Erklärung beschreibt, wie TOOYEI Geschäftsinformationen verarbeitet, die Sie über Website und begleitende Abläufe bereitstellen.",
      description: "Wie TOOYEI Anfrage-, Projekt- und Website-Daten erhebt, nutzt, schützt und verarbeitet.",
      lastUpdatedLabel: "Zuletzt aktualisiert",
      lastUpdated: updated,
      backHome: "Zur Startseite",
      sections: [
        { title: "Geltungsbereich und Verantwortlicher", body: `${legalName} ist für Informationen verantwortlich, die über diese Website, Anfragen, E-Mails, Muster, Angebote, Projektabstimmung und notwendige Admin-Abläufe verarbeitet werden.` },
        { title: "Erhobene Informationen", body: "Wir können Name, Unternehmen, Funktion, E-Mail, Telefon, Land oder Region, Zielmarkt, Produktanforderungen, Projektdateien, Anhänge und freiwillige Nachrichten erfassen." },
        { title: "Nutzung der Informationen", body: "Wir nutzen Informationen zur Beantwortung von Anfragen, Klärung von Spezifikationen, Erstellung von Mustern oder Angeboten, Exportabwicklung, Kommunikationsdokumentation, Verbesserung der Website sowie für Rechts-, Compliance- und Sicherheitsanforderungen." },
        { title: "Weitergabe und internationale Verarbeitung", body: "Informationen werden nur bei Bedarf mit internen Teams und Dienstleistern wie Logistik, Prüfung, Zahlung, IT oder Compliance geteilt. Für globale Kunden kann Verarbeitung über Länder oder Regionen hinweg erfolgen." },
        { title: "Aufbewahrung, Sicherheit und Rechte", body: "Wir speichern Informationen für Geschäfts-, Compliance- und Prüfzwecke und setzen angemessene Zugriffskontrollen ein. Sie können Auskunft, Berichtigung, Löschung oder Einschränkung verlangen." },
        { title: "Minderjährige, Aktualisierungen und Kontakt", body: `Die Website richtet sich an Geschäftskunden, nicht an Minderjährige. Aktualisierungen erscheinen hier. Datenschutzanfragen senden Sie an ${email}.` },
      ],
    },
    terms: {
      eyebrow: "Rechtliches / Bedingungen",
      title: "Nutzungsbedingungen",
      intro: "Mit dem Zugriff auf diese Website stimmen Sie den folgenden Grundregeln zu.",
      description: "TOOYEI Nutzungsbedingungen zu Inhalten, geistigem Eigentum, zulässiger Nutzung, Drittlinks und Haftungsgrenzen.",
      lastUpdatedLabel: "Zuletzt aktualisiert",
      lastUpdated: updated,
      backHome: "Zur Startseite",
      sections: [
        { title: "Annahme", body: `Diese Website wird von ${legalName} betrieben. Durch Besuch, Anfrage oder Nutzung von Inhalten akzeptieren Sie diese Bedingungen und geltendes Recht.` },
        { title: "Website-Inhalte", body: "Produktbilder, Spezifikationen, Zertifizierungen, Farben, Verpackungen und Anwendungshinweise dienen der allgemeinen Information und sind kein verbindliches Angebot. Endgültige Bedingungen ergeben sich aus schriftlicher Bestätigung." },
        { title: "Geistiges Eigentum", body: "Marken, Texte, Bilder, Layouts und Materialien gehören, soweit nicht anders angegeben, TOOYEI oder den jeweiligen Rechteinhabern und dürfen ohne Erlaubnis nicht kopiert oder irreführend genutzt werden." },
        { title: "Zulässige Nutzung", body: "Sie dürfen keine schädlichen Inhalte hochladen, Dienste stören, sensible Daten auslesen, TOOYEI imitieren oder die Website rechts-, handels- oder sicherheitswidrig nutzen." },
        { title: "Links zu Dritten", body: "Die Website kann auf soziale Medien, Karten, E-Mail, Downloads oder Drittanbieter-Tools verweisen. Diese Dienste unterliegen eigenen Bedingungen, Datenschutzregeln und Verfügbarkeit." },
        { title: "Haftungsausschluss und Aktualisierung", body: `Wir bemühen uns um korrekte Informationen, garantieren jedoch keine fehlerfreie oder ununterbrochene Website. Fragen bitte an ${email}.` },
      ],
    },
    cookies: {
      eyebrow: "Rechtliches / Cookies",
      title: "Cookie-Hinweis",
      intro: "Diese Seite erklärt Cookies und ähnliche lokale Speichertechnologien auf der TOOYEI Website.",
      description: "TOOYEI Cookie-Hinweis zu notwendigen Funktionen, Präferenzen, Analyse, Browsersteuerung und Kontakt.",
      lastUpdatedLabel: "Zuletzt aktualisiert",
      lastUpdated: updated,
      backHome: "Zur Startseite",
      sections: [
        { title: "Was Cookies sind", body: "Cookies speichern kleine Informationen im Browser, um Sitzungen zu erkennen, Spracheinstellungen zu merken oder Grundfunktionen zu ermöglichen." },
        { title: "Notwendige Cookies", body: "Notwendige Cookies unterstützen Sicherheit, Admin-Login, Formulare, Sprachauswahl und Kerninteraktionen. Einige Funktionen arbeiten ohne sie nicht korrekt." },
        { title: "Präferenzen", body: "Die Website kann Sprache, Region oder Oberflächenpräferenzen speichern, um wiederholte Auswahl zu vermeiden." },
        { title: "Analyse und Marketing", body: "Wenn zukünftig Analyse- oder Marketingtools eingesetzt werden, aktualisieren wir diesen Hinweis und stellen erforderliche Zustimmungs- oder Kontrolloptionen bereit." },
        { title: "Verwaltung", body: "Sie können Cookies in den Browsereinstellungen anzeigen, blockieren oder löschen. Das Deaktivieren notwendiger Cookies kann Login, Formulare oder Sprachwechsel beeinträchtigen." },
        { title: "Aktualisierung und Kontakt", body: `Bei Fragen zu Cookies kontaktieren Sie ${email}.` },
      ],
    },
  },
  fr: {
    privacy: {
      eyebrow: "Juridique / Confidentialité",
      title: "Politique de confidentialité",
      intro: "Cette politique explique comment TOOYEI traite les informations professionnelles transmises via le site et les échanges associés.",
      description: "Collecte, utilisation, protection et traitement des informations de demande, projet et navigation par TOOYEI.",
      lastUpdatedLabel: "Dernière mise à jour",
      lastUpdated: updated,
      backHome: "Retour à l’accueil",
      sections: [
        { title: "Champ d’application et responsable", body: `${legalName} est responsable des informations traitées via ce site, les demandes, e-mails, échantillons, devis, coordination de projet et opérations d’administration nécessaires.` },
        { title: "Informations collectées", body: "Nous pouvons collecter nom, société, fonction, e-mail, téléphone, pays ou région, marché cible, besoins produit, fichiers projet, pièces jointes et messages fournis volontairement." },
        { title: "Utilisation", body: "Ces informations servent à répondre aux demandes, confirmer les spécifications, préparer échantillons ou devis, coordonner l’export, conserver l’historique, améliorer le site et respecter les obligations légales, de conformité ou de sécurité." },
        { title: "Partage et traitement international", body: "Nous partageons les informations seulement si nécessaire avec équipes internes et prestataires de logistique, tests, paiement, IT ou conformité. Les données peuvent être traitées dans plusieurs pays ou régions." },
        { title: "Conservation, sécurité et droits", body: "Nous conservons les informations pour les besoins commerciaux, de conformité et d’audit avec des contrôles d’accès raisonnables. Vous pouvez demander accès, correction, suppression ou limitation." },
        { title: "Mineurs, mises à jour et contact", body: `Le site s’adresse aux professionnels et non aux mineurs. Les mises à jour seront publiées ici. Contact : ${email}.` },
      ],
    },
    terms: {
      eyebrow: "Juridique / Conditions",
      title: "Conditions d’utilisation",
      intro: "En accédant à ce site, vous acceptez les règles d’utilisation suivantes.",
      description: "Conditions d’utilisation TOOYEI relatives au contenu, à la propriété intellectuelle, à l’usage autorisé, aux liens tiers et aux limites de responsabilité.",
      lastUpdatedLabel: "Dernière mise à jour",
      lastUpdated: updated,
      backHome: "Retour à l’accueil",
      sections: [
        { title: "Acceptation", body: `Ce site est exploité par ${legalName}. En le visitant, en envoyant une demande ou en utilisant son contenu, vous acceptez ces conditions et la loi applicable.` },
        { title: "Contenu du site", body: "Images, spécifications, certifications, couleurs, emballages et usages produits sont fournis à titre informatif et ne constituent pas une offre ferme. Les conditions finales reposent sur une confirmation écrite." },
        { title: "Propriété intellectuelle", body: "Sauf mention contraire, marques, textes, images, mises en page et documents appartiennent à TOOYEI ou aux ayants droit concernés et ne peuvent être copiés ou utilisés de manière trompeuse sans autorisation." },
        { title: "Usage autorisé", body: "Vous ne devez pas téléverser de contenu malveillant, perturber le service, extraire des données sensibles, usurper TOOYEI ni utiliser le site contrairement à la loi, à la conformité commerciale ou à la sécurité." },
        { title: "Liens tiers", body: "Le site peut renvoyer vers réseaux sociaux, cartes, e-mail, téléchargements ou outils tiers, soumis à leurs propres conditions, politiques et disponibilité." },
        { title: "Responsabilité et mises à jour", body: `Nous cherchons l’exactitude sans garantir un site sans erreur ou interruption. Questions : ${email}.` },
      ],
    },
    cookies: {
      eyebrow: "Juridique / Cookies",
      title: "Avis sur les cookies",
      intro: "Cette page décrit les cookies et technologies de stockage local similaires susceptibles d’être utilisés sur le site TOOYEI.",
      description: "Avis cookies TOOYEI : fonctions essentielles, préférences, analyse, contrôles navigateur et contact.",
      lastUpdatedLabel: "Dernière mise à jour",
      lastUpdated: updated,
      backHome: "Retour à l’accueil",
      sections: [
        { title: "Définition", body: "Les cookies stockent de petites informations dans le navigateur pour reconnaître une session, mémoriser la langue ou prendre en charge les fonctions de base." },
        { title: "Cookies nécessaires", body: "Ils soutiennent la sécurité, la connexion admin, les formulaires, la langue et les interactions essentielles. Certaines fonctions peuvent échouer sans eux." },
        { title: "Préférences", body: "Le site peut mémoriser langue, région ou préférences d’interface pour éviter les sélections répétées." },
        { title: "Analyse et marketing", body: "Si des outils d’analyse ou marketing sont ajoutés, cet avis sera mis à jour et des options de consentement ou contrôle seront fournies si nécessaire." },
        { title: "Gestion", body: "Vous pouvez afficher, bloquer ou supprimer les cookies dans le navigateur. Bloquer les cookies nécessaires peut affecter connexion, formulaires ou changement de langue." },
        { title: "Contact", body: `Questions sur les cookies : ${email}.` },
      ],
    },
  },
  es: {
    privacy: {
      eyebrow: "Legal / Privacidad",
      title: "Política de privacidad",
      intro: "Esta política explica cómo TOOYEI trata la información comercial que usted envía por el sitio y flujos relacionados.",
      description: "Cómo TOOYEI recopila, usa, protege y trata información de consultas, proyectos y navegación.",
      lastUpdatedLabel: "Última actualización",
      lastUpdated: updated,
      backHome: "Volver al inicio",
      sections: [
        { title: "Alcance y responsable", body: `${legalName} es responsable de la información tratada a través de este sitio, consultas, correos, muestras, cotizaciones, coordinación de proyectos y operaciones administrativas necesarias.` },
        { title: "Información recopilada", body: "Podemos recopilar nombre, empresa, cargo, email, teléfono, país o región, mercado objetivo, requisitos de producto, archivos del proyecto, adjuntos y mensajes proporcionados voluntariamente." },
        { title: "Uso de la información", body: "Usamos la información para responder consultas, confirmar especificaciones, preparar muestras o cotizaciones, coordinar exportaciones, mantener registros, mejorar el sitio y cumplir obligaciones legales, de seguridad o cumplimiento." },
        { title: "Compartición y tratamiento internacional", body: "Compartimos información solo cuando es necesario con equipos internos y proveedores de logística, pruebas, pagos, IT o cumplimiento. Puede tratarse en distintos países o regiones." },
        { title: "Conservación, seguridad y derechos", body: "Conservamos la información por necesidades comerciales, de cumplimiento y auditoría, con controles razonables de acceso. Puede solicitar acceso, corrección, eliminación o limitación." },
        { title: "Menores, cambios y contacto", body: `El sitio está dirigido a empresas, no a menores. Las actualizaciones se publicarán aquí. Contacto: ${email}.` },
      ],
    },
    terms: {
      eyebrow: "Legal / Términos",
      title: "Términos de uso",
      intro: "Al acceder o usar este sitio, acepta las siguientes reglas básicas.",
      description: "Términos del sitio TOOYEI sobre contenido, propiedad intelectual, uso aceptable, enlaces externos y límites de responsabilidad.",
      lastUpdatedLabel: "Última actualización",
      lastUpdated: updated,
      backHome: "Volver al inicio",
      sections: [
        { title: "Aceptación", body: `Este sitio es operado por ${legalName}. Al visitarlo, enviar consultas o usar su contenido, acepta estos términos y las leyes aplicables.` },
        { title: "Contenido del sitio", body: "Imágenes, especificaciones, certificaciones, colores, embalaje y aplicaciones son información general y no constituyen una oferta vinculante. Las condiciones finales dependen de confirmación escrita." },
        { title: "Propiedad intelectual", body: "Salvo indicación contraria, marcas, textos, imágenes, diseño y materiales pertenecen a TOOYEI o a sus titulares y no pueden copiarse ni usarse de forma engañosa sin permiso." },
        { title: "Uso aceptable", body: "No debe cargar contenido malicioso, interferir con el servicio, extraer datos sensibles, suplantar a TOOYEI ni usar el sitio contra la ley, el cumplimiento comercial o la seguridad." },
        { title: "Enlaces de terceros", body: "El sitio puede enlazar redes sociales, mapas, email, descargas o herramientas externas, sujetas a sus propios términos, privacidad y disponibilidad." },
        { title: "Responsabilidad y cambios", body: `Intentamos mantener la información correcta, pero no garantizamos ausencia de errores o interrupciones. Consultas: ${email}.` },
      ],
    },
    cookies: {
      eyebrow: "Legal / Cookies",
      title: "Aviso de cookies",
      intro: "Esta página explica las cookies y tecnologías similares que pueden usarse en el sitio TOOYEI.",
      description: "Aviso de cookies TOOYEI sobre funciones esenciales, preferencias, análisis, controles del navegador y contacto.",
      lastUpdatedLabel: "Última actualización",
      lastUpdated: updated,
      backHome: "Volver al inicio",
      sections: [
        { title: "Qué son", body: "Las cookies guardan pequeñas cantidades de información en el navegador para reconocer sesiones, recordar idioma o apoyar funciones básicas." },
        { title: "Cookies esenciales", body: "Sostienen seguridad, login admin, formularios, idioma e interacciones principales. Algunas funciones pueden fallar sin ellas." },
        { title: "Preferencias", body: "El sitio puede recordar idioma, región o preferencias de interfaz para reducir selecciones repetidas." },
        { title: "Análisis y marketing", body: "Si se agregan herramientas de análisis o marketing, actualizaremos este aviso y ofreceremos opciones de consentimiento o control cuando corresponda." },
        { title: "Gestión", body: "Puede ver, bloquear o borrar cookies en el navegador. Desactivar cookies esenciales puede afectar login, formularios o cambio de idioma." },
        { title: "Contacto", body: `Preguntas sobre cookies: ${email}.` },
      ],
    },
  },
  ru: {
    privacy: {
      eyebrow: "Правовая информация / Конфиденциальность",
      title: "Политика конфиденциальности",
      intro: "Эта политика объясняет, как TOOYEI обрабатывает деловую информацию, которую вы передаете через сайт и связанные процессы.",
      description: "Как TOOYEI собирает, использует, защищает и обрабатывает данные запросов, проектов и посещения сайта.",
      lastUpdatedLabel: "Последнее обновление",
      lastUpdated: updated,
      backHome: "На главную",
      sections: [
        { title: "Область действия и оператор", body: `${legalName} отвечает за информацию, обрабатываемую через сайт, запросы, письма, образцы, коммерческие предложения, проектную координацию и необходимые административные операции.` },
        { title: "Какие данные мы собираем", body: "Мы можем собирать имя, компанию, должность, e-mail, телефон, страну или регион, целевой рынок, требования к продукции, проектные файлы, вложения и добровольные сообщения." },
        { title: "Цели использования", body: "Данные используются для ответа на запросы, уточнения спецификаций, подготовки образцов или предложений, экспортной координации, ведения истории коммуникаций, улучшения сайта и выполнения требований закона, комплаенса и безопасности." },
        { title: "Передача и международная обработка", body: "Мы передаем информацию только при необходимости внутренним командам и поставщикам логистики, испытаний, платежей, IT или комплаенса. Данные могут обрабатываться в разных странах или регионах." },
        { title: "Хранение, безопасность и права", body: "Мы храним данные для деловых, комплаенс- и аудиторских целей и применяем разумный контроль доступа. Вы можете запросить доступ, исправление, удаление или ограничение обработки." },
        { title: "Несовершеннолетние, обновления и контакт", body: `Сайт предназначен для бизнеса, а не для несовершеннолетних. Обновления публикуются здесь. Запросы: ${email}.` },
      ],
    },
    terms: {
      eyebrow: "Правовая информация / Условия",
      title: "Условия использования",
      intro: "Используя этот сайт, вы соглашаетесь с приведенными ниже правилами.",
      description: "Условия сайта TOOYEI о контенте, интеллектуальной собственности, допустимом использовании, сторонних ссылках и ограничении ответственности.",
      lastUpdatedLabel: "Последнее обновление",
      lastUpdated: updated,
      backHome: "На главную",
      sections: [
        { title: "Принятие условий", body: `Сайт управляется ${legalName}. Посещая сайт, отправляя запросы или используя контент, вы соглашаетесь с этими условиями и применимым законодательством.` },
        { title: "Контент сайта", body: "Изображения, спецификации, сертификаты, цвета, упаковка и области применения носят информационный характер и не являются обязательной офертой. Итоговые условия подтверждаются письменно сторонами." },
        { title: "Интеллектуальная собственность", body: "Если не указано иное, товарные знаки, тексты, изображения, макеты и материалы принадлежат TOOYEI или соответствующим правообладателям и не могут копироваться или использоваться вводящим в заблуждение образом без разрешения." },
        { title: "Допустимое использование", body: "Запрещено загружать вредоносный контент, мешать работе сервиса, извлекать чувствительные данные, выдавать себя за TOOYEI или использовать сайт с нарушением закона, торгового комплаенса или безопасности." },
        { title: "Сторонние ссылки", body: "Сайт может содержать ссылки на социальные сети, карты, e-mail, загрузки или внешние инструменты. Они регулируются собственными условиями, политиками и доступностью." },
        { title: "Ответственность и обновления", body: `Мы стремимся к точности, но не гарантируем отсутствие ошибок или перерывов. Вопросы: ${email}.` },
      ],
    },
    cookies: {
      eyebrow: "Правовая информация / Cookies",
      title: "Уведомление о cookies",
      intro: "Эта страница описывает cookies и похожие технологии локального хранения, которые могут использоваться на сайте TOOYEI.",
      description: "Уведомление TOOYEI о cookies: необходимые функции, предпочтения, аналитика, настройки браузера и контакт.",
      lastUpdatedLabel: "Последнее обновление",
      lastUpdated: updated,
      backHome: "На главную",
      sections: [
        { title: "Что такое cookies", body: "Cookies сохраняют небольшие фрагменты информации в браузере для распознавания сеанса, запоминания языка и поддержки базовых функций." },
        { title: "Необходимые cookies", body: "Они поддерживают безопасность, вход администратора, формы, выбор языка и основные взаимодействия. Без них часть функций может работать некорректно." },
        { title: "Предпочтения", body: "Сайт может запоминать язык, регион или настройки интерфейса, чтобы не требовать повторного выбора." },
        { title: "Аналитика и маркетинг", body: "Если в будущем будут добавлены такие инструменты, мы обновим уведомление и при необходимости предоставим выбор согласия или управления." },
        { title: "Управление", body: "Вы можете просматривать, блокировать или удалять cookies в браузере. Отключение необходимых cookies может повлиять на вход, формы или переключение языка." },
        { title: "Контакт", body: `Вопросы о cookies: ${email}.` },
      ],
    },
  },
  ja: {
    privacy: {
      eyebrow: "法務 / プライバシー",
      title: "プライバシーポリシー",
      intro: "本ポリシーは、TOOYEI がウェブサイトおよび関連業務で受け取るビジネス情報の取り扱いを説明します。",
      description: "TOOYEI による問い合わせ、プロジェクト、サイト利用情報の収集、利用、保護、処理について。",
      lastUpdatedLabel: "最終更新",
      lastUpdated: updated,
      backHome: "ホームへ戻る",
      sections: [
        { title: "範囲と管理者", body: `${legalName} は、本サイト、問い合わせ、メール、サンプル、見積、プロジェクト調整、必要な管理業務で処理される情報の管理者です。` },
        { title: "収集する情報", body: "氏名、会社名、役職、メール、電話、国または地域、対象市場、製品要件、プロジェクト資料、添付ファイル、任意のメッセージを収集する場合があります。" },
        { title: "利用目的", body: "問い合わせ対応、仕様確認、サンプルや見積作成、輸出調整、連絡記録、サイト改善、法令・コンプライアンス・安全上の要件への対応に利用します。" },
        { title: "共有と国際処理", body: "必要な範囲で社内チーム、物流、試験、決済、IT、コンプライアンス関連のサービス提供者と共有します。グローバル対応のため、国や地域をまたいで処理される場合があります。" },
        { title: "保管、安全、権利", body: "業務、コンプライアンス、監査に必要な期間保管し、合理的なアクセス管理を行います。アクセス、訂正、削除、処理制限を請求できます。" },
        { title: "未成年、更新、連絡先", body: `本サイトは企業向けであり未成年を対象としていません。更新は本ページに掲載します。連絡先: ${email}。` },
      ],
    },
    terms: {
      eyebrow: "法務 / 規約",
      title: "利用規約",
      intro: "本サイトにアクセスまたは利用することで、以下の基本規則に同意したものとします。",
      description: "TOOYEI サイトのコンテンツ、知的財産、許容される利用、外部リンク、責任制限に関する規約。",
      lastUpdatedLabel: "最終更新",
      lastUpdated: updated,
      backHome: "ホームへ戻る",
      sections: [
        { title: "同意", body: `本サイトは ${legalName} が運営しています。閲覧、問い合わせ送信、コンテンツ利用により、本規約および適用法に従うものとします。` },
        { title: "サイト内容", body: "製品画像、仕様、認証、色、包装、用途説明は一般情報であり、拘束力あるオファーではありません。最終条件は当事者間の書面確認に基づきます。" },
        { title: "知的財産", body: "別段の表示がない限り、商標、文章、画像、レイアウト、資料は TOOYEI または権利者に帰属し、許可なく複製または誤認を招く商業利用はできません。" },
        { title: "許容される利用", body: "悪意あるコンテンツのアップロード、サービス妨害、機密データ取得、TOOYEI のなりすまし、法令・貿易コンプライアンス・安全性に反する利用は禁止されます。" },
        { title: "第三者リンク", body: "本サイトには SNS、地図、メール、ダウンロード、外部ツールへのリンクが含まれる場合があり、それぞれの規約、プライバシー、可用性に従います。" },
        { title: "免責と更新", body: `正確性に努めますが、常に無誤りまたは無停止であることは保証しません。お問い合わせ: ${email}。` },
      ],
    },
    cookies: {
      eyebrow: "法務 / Cookies",
      title: "Cookie に関するお知らせ",
      intro: "本ページは TOOYEI サイトで使用される可能性のある Cookie および類似のローカル保存技術を説明します。",
      description: "TOOYEI の Cookie 通知。必要機能、設定、分析、ブラウザ管理、連絡先を含みます。",
      lastUpdatedLabel: "最終更新",
      lastUpdated: updated,
      backHome: "ホームへ戻る",
      sections: [
        { title: "Cookie とは", body: "Cookie はセッション識別、言語設定の記憶、基本機能のためにブラウザへ少量の情報を保存します。" },
        { title: "必要な Cookie", body: "安全性、管理者ログイン、フォーム送信、言語選択、基本操作を支えます。無効化すると一部機能が動作しない場合があります。" },
        { title: "設定", body: "サイトは言語、地域、表示設定を記憶し、繰り返し選択を減らす場合があります。" },
        { title: "分析とマーケティング", body: "将来これらのツールを導入する場合、本通知を更新し、必要に応じて同意または管理の選択肢を提供します。" },
        { title: "管理方法", body: "ブラウザ設定で Cookie を確認、ブロック、削除できます。必要 Cookie を無効にするとログイン、フォーム、言語切替に影響する場合があります。" },
        { title: "連絡先", body: `Cookie に関する質問: ${email}。` },
      ],
    },
  },
  it: {
    privacy: {
      eyebrow: "Legale / Privacy",
      title: "Informativa sulla privacy",
      intro: "Questa informativa spiega come TOOYEI tratta le informazioni commerciali inviate tramite il sito e i flussi correlati.",
      description: "Come TOOYEI raccoglie, usa, protegge e tratta informazioni su richieste, progetti e sito.",
      lastUpdatedLabel: "Ultimo aggiornamento",
      lastUpdated: updated,
      backHome: "Torna alla home",
      sections: [
        { title: "Ambito e titolare", body: `${legalName} è responsabile delle informazioni trattate tramite questo sito, richieste, email, campioni, preventivi, coordinamento progetti e operazioni amministrative necessarie.` },
        { title: "Informazioni raccolte", body: "Possiamo raccogliere nome, azienda, ruolo, email, telefono, paese o regione, mercato target, requisiti prodotto, file di progetto, allegati e messaggi forniti volontariamente." },
        { title: "Uso delle informazioni", body: "Usiamo i dati per rispondere alle richieste, confermare specifiche, preparare campioni o preventivi, coordinare export, conservare comunicazioni, migliorare il sito e rispettare obblighi legali, di conformità o sicurezza." },
        { title: "Condivisione e trattamento internazionale", body: "Condividiamo solo se necessario con team interni e fornitori di logistica, test, pagamenti, IT o compliance. I dati possono essere trattati in paesi o regioni diversi." },
        { title: "Conservazione, sicurezza e diritti", body: "Conserviamo i dati per esigenze commerciali, di conformità e audit, con controlli di accesso ragionevoli. Può richiedere accesso, correzione, eliminazione o limitazione." },
        { title: "Minori, aggiornamenti e contatti", body: `Il sito è destinato a utenti business, non a minori. Gli aggiornamenti saranno pubblicati qui. Contatto: ${email}.` },
      ],
    },
    terms: {
      eyebrow: "Legale / Termini",
      title: "Condizioni d’uso",
      intro: "Accedendo o usando questo sito, accetta le seguenti regole di base.",
      description: "Condizioni TOOYEI su contenuti, proprietà intellettuale, uso consentito, link di terzi e limiti di responsabilità.",
      lastUpdatedLabel: "Ultimo aggiornamento",
      lastUpdated: updated,
      backHome: "Torna alla home",
      sections: [
        { title: "Accettazione", body: `Questo sito è gestito da ${legalName}. Visitandolo, inviando richieste o usando contenuti, accetta questi termini e le leggi applicabili.` },
        { title: "Contenuto del sito", body: "Immagini, specifiche, certificazioni, colori, imballaggi e applicazioni sono informazioni generali e non costituiscono offerta vincolante. Le condizioni finali dipendono dalla conferma scritta." },
        { title: "Proprietà intellettuale", body: "Salvo diversa indicazione, marchi, testi, immagini, layout e materiali appartengono a TOOYEI o ai rispettivi titolari e non possono essere copiati o usati in modo fuorviante senza permesso." },
        { title: "Uso consentito", body: "Non deve caricare contenuti dannosi, interferire con il servizio, estrarre dati sensibili, impersonare TOOYEI o usare il sito contro legge, compliance commerciale o sicurezza." },
        { title: "Link di terzi", body: "Il sito può collegare social media, mappe, email, download o strumenti esterni, soggetti ai rispettivi termini, privacy e disponibilità." },
        { title: "Responsabilità e aggiornamenti", body: `Cerchiamo accuratezza, ma non garantiamo assenza di errori o interruzioni. Domande: ${email}.` },
      ],
    },
    cookies: {
      eyebrow: "Legale / Cookie",
      title: "Informativa sui cookie",
      intro: "Questa pagina spiega cookie e tecnologie simili che possono essere usati sul sito TOOYEI.",
      description: "Informativa cookie TOOYEI su funzioni essenziali, preferenze, analisi, controlli browser e contatti.",
      lastUpdatedLabel: "Ultimo aggiornamento",
      lastUpdated: updated,
      backHome: "Torna alla home",
      sections: [
        { title: "Cosa sono", body: "I cookie salvano piccole informazioni nel browser per riconoscere sessioni, ricordare la lingua o supportare funzioni di base." },
        { title: "Cookie essenziali", body: "Supportano sicurezza, login admin, moduli, lingua e interazioni principali. Alcune funzioni potrebbero non funzionare senza di essi." },
        { title: "Preferenze", body: "Il sito può ricordare lingua, regione o preferenze di interfaccia per ridurre selezioni ripetute." },
        { title: "Analisi e marketing", body: "Se in futuro saranno aggiunti strumenti di analisi o marketing, aggiorneremo questa informativa e forniremo opzioni di consenso o controllo se richieste." },
        { title: "Gestione", body: "Può vedere, bloccare o eliminare i cookie nelle impostazioni del browser. Disabilitare quelli essenziali può influire su login, moduli o cambio lingua." },
        { title: "Contatti", body: `Domande sui cookie: ${email}.` },
      ],
    },
  },
  ar: {
    privacy: {
      eyebrow: "قانوني / الخصوصية",
      title: "سياسة الخصوصية",
      intro: "توضح هذه السياسة كيف تعالج TOOYEI معلومات الأعمال التي ترسلها عبر الموقع والعمليات المرتبطة به.",
      description: "كيفية جمع TOOYEI لمعلومات الاستفسارات والمشاريع والموقع واستخدامها وحمايتها ومعالجتها.",
      lastUpdatedLabel: "آخر تحديث",
      lastUpdated: updated,
      backHome: "العودة إلى الرئيسية",
      sections: [
        { title: "النطاق والجهة المسؤولة", body: `${legalName} مسؤولة عن المعلومات التي تتم معالجتها عبر هذا الموقع، بما في ذلك الاستفسارات والبريد الإلكتروني والعينات وعروض الأسعار وتنسيق المشاريع والعمليات الإدارية الضرورية.` },
        { title: "المعلومات التي نجمعها", body: "قد نجمع الاسم، الشركة، المنصب، البريد الإلكتروني، الهاتف، الدولة أو المنطقة، السوق المستهدف، متطلبات المنتج، ملفات المشروع، المرفقات والرسائل التي تقدمها طوعا." },
        { title: "كيفية الاستخدام", body: "نستخدم المعلومات للرد على الاستفسارات، تأكيد المواصفات، إعداد العينات أو عروض الأسعار، تنسيق التصدير، حفظ سجلات التواصل، تحسين الموقع وتلبية المتطلبات القانونية والامتثالية والأمنية." },
        { title: "المشاركة والمعالجة الدولية", body: "لا نشارك المعلومات إلا عند الحاجة مع الفرق الداخلية ومقدمي خدمات مثل اللوجستيات والاختبار والدفع وتقنية المعلومات والامتثال. قد تتم المعالجة عبر دول أو مناطق مختلفة." },
        { title: "الاحتفاظ والأمان والحقوق", body: "نحتفظ بالمعلومات لاحتياجات العمل والامتثال والتدقيق مع ضوابط وصول معقولة. يمكنك طلب الوصول أو التصحيح أو الحذف أو تقييد المعالجة." },
        { title: "القصر والتحديثات والتواصل", body: `الموقع موجه للأعمال وليس للقصر. تنشر التحديثات هنا. لطلبات الخصوصية: ${email}.` },
      ],
    },
    terms: {
      eyebrow: "قانوني / الشروط",
      title: "شروط الاستخدام",
      intro: "باستخدام هذا الموقع أو الوصول إليه، فإنك توافق على القواعد الأساسية التالية.",
      description: "شروط موقع TOOYEI حول المحتوى والملكية الفكرية والاستخدام المقبول وروابط الطرف الثالث وحدود المسؤولية.",
      lastUpdatedLabel: "آخر تحديث",
      lastUpdated: updated,
      backHome: "العودة إلى الرئيسية",
      sections: [
        { title: "القبول", body: `يتم تشغيل هذا الموقع بواسطة ${legalName}. بزيارته أو إرسال استفسارات أو استخدام المحتوى، توافق على هذه الشروط والقوانين المعمول بها.` },
        { title: "محتوى الموقع", body: "صور المنتجات والمواصفات والشهادات والألوان والتغليف وملاحظات الاستخدام هي معلومات عامة وليست عرضا ملزما. تعتمد الشروط النهائية على تأكيد كتابي بين الأطراف." },
        { title: "الملكية الفكرية", body: "ما لم يذكر خلاف ذلك، فإن العلامات والنصوص والصور والتخطيطات والمواد تعود إلى TOOYEI أو أصحاب الحقوق ولا يجوز نسخها أو استخدامها بطريقة مضللة دون إذن." },
        { title: "الاستخدام المقبول", body: "لا يجوز رفع محتوى ضار، تعطيل الخدمة، استخراج بيانات حساسة، انتحال TOOYEI أو استخدام الموقع بما يخالف القانون أو الامتثال التجاري أو الأمن." },
        { title: "روابط الطرف الثالث", body: "قد يتضمن الموقع روابط إلى وسائل التواصل أو الخرائط أو البريد أو التنزيلات أو أدوات خارجية، وتخضع لشروطها وسياساتها وتوفرها." },
        { title: "المسؤولية والتحديثات", body: `نحاول إبقاء المعلومات دقيقة، لكننا لا نضمن خلو الموقع من الأخطاء أو الانقطاع. للأسئلة: ${email}.` },
      ],
    },
    cookies: {
      eyebrow: "قانوني / ملفات تعريف الارتباط",
      title: "إشعار ملفات تعريف الارتباط",
      intro: "توضح هذه الصفحة ملفات تعريف الارتباط وتقنيات التخزين المحلي المشابهة التي قد يستخدمها موقع TOOYEI.",
      description: "إشعار TOOYEI حول ملفات تعريف الارتباط للوظائف الأساسية والتفضيلات والتحليلات وإدارة المتصفح والتواصل.",
      lastUpdatedLabel: "آخر تحديث",
      lastUpdated: updated,
      backHome: "العودة إلى الرئيسية",
      sections: [
        { title: "ما هي", body: "تخزن ملفات تعريف الارتباط معلومات صغيرة في المتصفح للتعرف على الجلسات وتذكر اللغة ودعم وظائف الموقع الأساسية." },
        { title: "الملفات الضرورية", body: "تدعم الأمان وتسجيل دخول الإدارة والنماذج واختيار اللغة والتفاعلات الأساسية. قد لا تعمل بعض الوظائف دونها." },
        { title: "التفضيلات", body: "قد يتذكر الموقع اللغة أو المنطقة أو تفضيلات الواجهة لتقليل الاختيارات المتكررة." },
        { title: "التحليلات والتسويق", body: "إذا تمت إضافة أدوات تحليل أو تسويق مستقبلا، فسنحدث هذا الإشعار ونوفر خيارات الموافقة أو التحكم عند الحاجة." },
        { title: "الإدارة", body: "يمكنك عرض الملفات أو حظرها أو حذفها من إعدادات المتصفح. تعطيل الملفات الضرورية قد يؤثر على الدخول والنماذج وتبديل اللغة." },
        { title: "التواصل", body: `للأسئلة حول ملفات تعريف الارتباط: ${email}.` },
      ],
    },
  },
};
